export const price = {
    econom: {
        // aero: {
            // andreevka: ,
            // aidanil; ,
            // bahchisaray; ,
            // belogorsk; ,
            // vilino; ,
            // krasnokamenka; ,
            // karasan; ,
            // koreiz; ,
            // kurpaty; ,
            // krasnogvardeiskoe; ,
            // laspi; ,
            // lenino; ,
            // lineinoe; ,
            // lybimovka; ,
            // maliymayak; ,
            // mishor; ,
            // mirniy; ,
            // massandra; ,
            // novoozernoe; ,
            // niznayaoreanda; ,
            // nikita; ,
            // okunevka; ,
            // otradnoe; ,
            // oliva; ,
            // orlinoe; ,
            // opolznevoe; ,
            // uglovoe: ,
            // pushkino: ,
            // privetnoe: ,
            // peschanoe: ,
            // perevalnoe: ,
            // solnechnoe: ,
            // frunze: ,
            // molochnoe: ,
            // shelkino: ,
            // mriya: ,
            // taygan: ,
        //     alushta : 1600,
        //     yalta : 2300,
        //     evpatoriya : 1800,
        //     zaozernoe : 2100,
        //     shtormovoe : 2200,
        //     popovka : 2400,
        //     olenevka : 3300,
        //     chernomorskoe : 3100,
        //     saki : 1500,
        //     priboy : 1600,
        //     novofedorovka : 1500,
        //     nikolaevka : 1500,
        //     beregovoe_ubk : 2500,
        //     beregovoe_nik : 1600,
        //     beregovoe_feo : 3200,
        //     peschanoe : 1700,
        //     sevastopol : 2300,
        //     balaklava : 2300,
        //     orlovka : 2000,
        //     kacha : 2000,
        //     sudak : 2500,
        //     noviysvet: 2700,                
        //     feodosiya : 3000,
        //     kerch : 4500,
        //     koktebel : 3000,
        //     ordzhonikidze : 3000,
        //     ribache : 2500,
        //     solnechnogorskoe : 2300,
        //     malorechenskoe : 2300,
        //     partenit : 1700,
        //     gurzuf : 1800,
        //     livadiya : 2400,
        //     gaspra : 2500,
        //     alupka : 2600,
        //     simeiz : 2600,
        //     kaciveli : 2600,
        //     ponizovka : 2600,
        //     sanatornoye : 2600,
        //     foros : 2600
        // },
        trainstation: {
            andreevka: 1650,
            aidanil: 1950,
            bahchisaray: 1250,
            belogorsk: 1250,
            vilino: 1650,
            krasnokamenka: 1950,
            karasan: 1650,
            koreiz: 2450,
            kurpaty: 2450,
            krasnogvardeiskoe: 1950,
            laspi: 2450,
            lenino: 3250,
            lineinoe: 2450,
            lybimovka: 1950,
            maliymayak: 1650,
            mishor: 2450,
            mirniy: 2450,
            massandra: 2150,
            novoozernoe: 2450,
            niznayaoreanda: 2450,
            nikita: 1950,
            okunevka: 2450,
            otradnoe: 2150,
            oliva: 2450,
            orlinoe: 2450,
            opolznevoe: 2450,
            uglovoe: 1750,
            pushkino: 1650,
            privetnoe: 2450,
            peschanoe: 1650,
            perevalnoe: 950,
            solnechnoe: 1850,
            frunze: 1650,
            molochnoe: 2450,
            shelkino: 3450,
            mriya: 2450,
            taygan: 1950,
            alushta : 1250,
            yalta : 2250,
            evpatoriya : 1950,
            zaozernoe : 2150,
            shtormovoe : 2450,
            popovka : 2450,
            olenevka : 2950,
            chernomorskoe : 2650,
            saki : 1250,
            priboy : 1650,
            novofedorovka : 1450,
            nikolaevka : 1250,
            beregovoe_ubk : 2450,
            beregovoe_nik : 1650,
            beregovoe_feo : 2450,
            peschanoe : 1650,
            sevastopol : 2250,
            balaklava : 2150,
            orlovka : 1650,
            kacha : 1650,
            sudak : 2250,
            noviysvet: 2450,                
            feodosiya : 2250,
            kerch : 4950,
            koktebel : 2250,
            ordzhonikidze : 2450,
            ribache : 2250,
            solnechnogorskoe : 2250,
            malorechenskoe : 2250,
            partenit : 1650,
            gurzuf : 1950,
            livadiya : 2150,
            gaspra : 2450,
            alupka : 2450,
            simeiz : 2450,
            kaciveli : 2450,
            ponizovka : 2450,
            sanatornoye : 2450,
            foros : 2450
        }
    },
    comfort: {
        // aero: {
            // andreevka: ,
            // aidanil; ,
            // bahchisaray; ,
            // belogorsk; ,
            // vilino; ,
            // krasnokamenka; ,
            // karasan; ,
            // koreiz; ,
            // kurpaty; ,
            // krasnogvardeiskoe; ,
            // laspi; ,
            // lenino; ,
            // lineinoe; ,
            // lybimovka; ,
            // maliymayak; ,
            // mishor; ,
            // mirniy; ,
            // massandra; ,
            // novoozernoe; ,
            // niznayaoreanda; ,
            // nikita; ,
            // okunevka; ,
            // otradnoe; ,
            // oliva; ,
            // orlinoe; ,
            // opolznevoe; ,
            // uglovoe: ,
            // pushkino: ,
            // privetnoe: ,
            // peschanoe: ,
            // perevalnoe: ,
            // solnechnoe: ,
            // frunze: ,
            // molochnoe: ,
            // shelkino: ,
            // mriya: ,
            // taygan: ,
        //     alushta : 1600,
        //     yalta : 2300,
        //     evpatoriya : 1800,
        //     zaozernoe : 2100,
        //     shtormovoe : 2200,
        //     popovka : 2400,
        //     olenevka : 3300,
        //     chernomorskoe : 3100,
        //     saki : 1500,
        //     priboy : 1600,
        //     novofedorovka : 1500,
        //     nikolaevka : 1500,
        //     beregovoe_ubk : 2500,
        //     beregovoe_nik : 1600,
        //     beregovoe_feo : 3200,
        //     peschanoe : 1700,
        //     sevastopol : 2300,
        //     balaklava : 2300,
        //     orlovka : 2000,
        //     kacha : 2000,
        //     sudak : 2500,
        //     noviysvet: 2700,                
        //     feodosiya : 3000,
        //     kerch : 4500,
        //     koktebel : 3000,
        //     ordzhonikidze : 3000,
        //     ribache : 2500,
        //     solnechnogorskoe : 2300,
        //     malorechenskoe : 2300,
        //     partenit : 1700,
        //     gurzuf : 1800,
        //     livadiya : 2400,
        //     gaspra : 2500,
        //     alupka : 2600,
        //     simeiz : 2600,
        //     kaciveli : 2600,
        //     ponizovka : 2600,
        //     sanatornoye : 2600,
        //     foros : 2600
        // },
        trainstation: {
            andreevka: 1950,
            aidanil: 2250,
            bahchisaray: 1650,
            belogorsk: 1650,
            vilino: 1950,
            krasnokamenka: 2250,
            karasan: 1950,
            koreiz: 2950,
            kurpaty: 2950,
            krasnogvardeiskoe: 2450,
            laspi: 2950,
            lenino: 3750,
            lineinoe: 2950,
            lybimovka: 2450,
            maliymayak: 1950,
            mishor: 2950,
            mirniy: 2950,
            massandra: 2450,
            novoozernoe: 2950,
            niznayaoreanda: 2950,
            nikita: 2450,
            okunevka: 3250,
            otradnoe: 2450,
            oliva: 2950,
            orlinoe: 2950,
            opolznevoe: 2950,
            uglovoe: 1950,
            pushkino: 1950,
            privetnoe: 2950,
            peschanoe: 1950,
            perevalnoe: 1250,
            solnechnoe: 2250,
            frunze: 1950,
            molochnoe: 2950,
            shelkino: 3950,
            mriya: 2950,
            taygan: 2450,
            alushta : 1650,
            yalta : 2450,
            evpatoriya : 2450,
            zaozernoe : 2450,
            shtormovoe : 2950,
            popovka : 2950,
            olenevka : 3250,
            chernomorskoe : 2950,
            saki : 1650,
            priboy : 1950,
            novofedorovka : 1750,
            nikolaevka : 1650,
            beregovoe_ubk : 2950,
            beregovoe_nik : 1950,
            beregovoe_feo : 2950,
            peschanoe : 1950,
            sevastopol : 2450,
            balaklava : 2350,
            orlovka : 1950,
            kacha : 1950,
            sudak : 2450,
            noviysvet: 2950,                
            feodosiya : 2450,
            kerch : 5950,
            koktebel : 2450,
            ordzhonikidze : 2650,
            ribache : 2450,
            solnechnogorskoe : 2450,
            malorechenskoe : 2450,
            partenit : 1950,
            gurzuf : 2250,
            livadiya : 2350,
            gaspra : 2950,
            alupka : 2950,
            simeiz : 2950,
            kaciveli : 2950,
            ponizovka : 2950,
            sanatornoye : 2950,
            foros : 2950
        }
    },
    business: {
        // aero: {
            // andreevka: ,
            // aidanil; ,
            // bahchisaray; ,
            // belogorsk; ,
            // vilino; ,
            // krasnokamenka; ,
            // karasan; ,
            // koreiz; ,
            // kurpaty; ,
            // krasnogvardeiskoe; ,
            // laspi; ,
            // lenino; ,
            // lineinoe; ,
            // lybimovka; ,
            // maliymayak; ,
            // mishor; ,
            // mirniy; ,
            // massandra; ,
            // novoozernoe; ,
            // niznayaoreanda; ,
            // nikita; ,
            // okunevka; ,
            // otradnoe; ,
            // oliva; ,
            // orlinoe; ,
            // opolznevoe; ,
            // uglovoe: ,
            // pushkino: ,
            // privetnoe: ,
            // peschanoe: ,
            // perevalnoe: ,
            // solnechnoe: ,
            // frunze: ,
            // molochnoe: ,
            // shelkino: ,
            // mriya: ,
            // taygan: ,
        //     alushta : 1600,
        //     yalta : 2300,
        //     evpatoriya : 1800,
        //     zaozernoe : 2100,
        //     shtormovoe : 2200,
        //     popovka : 2400,
        //     olenevka : 3300,
        //     chernomorskoe : 3100,
        //     saki : 1500,
        //     priboy : 1600,
        //     novofedorovka : 1500,
        //     nikolaevka : 1500,
        //     beregovoe_ubk : 2500,
        //     beregovoe_nik : 1600,
        //     beregovoe_feo : 3200,
        //     peschanoe : 1700,
        //     sevastopol : 2300,
        //     balaklava : 2300,
        //     orlovka : 2000,
        //     kacha : 2000,
        //     sudak : 2500,
        //     noviysvet: 2700,                
        //     feodosiya : 3000,
        //     kerch : 4500,
        //     koktebel : 3000,
        //     ordzhonikidze : 3000,
        //     ribache : 2500,
        //     solnechnogorskoe : 2300,
        //     malorechenskoe : 2300,
        //     partenit : 1700,
        //     gurzuf : 1800,
        //     livadiya : 2400,
        //     gaspra : 2500,
        //     alupka : 2600,
        //     simeiz : 2600,
        //     kaciveli : 2600,
        //     ponizovka : 2600,
        //     sanatornoye : 2600,
        //     foros : 2600
        // },
        trainstation: {
            andreevka: 3950,
            aidanil: 3950,
            bahchisaray: 3450,
            belogorsk: 3450,
            vilino: 3950,
            krasnokamenka: 3950,
            karasan: 3950,
            koreiz: 4950,
            kurpaty: 4950,
            krasnogvardeiskoe: 3950,
            laspi: 4950,
            lenino: 6950,
            lineinoe: 4950,
            lybimovka: 3950,
            maliymayak: 3950,
            mishor: 4950,
            mirniy: 4950,
            massandra: 4450,
            novoozernoe: 4950,
            niznayaoreanda: 4950,
            nikita: 4450,
            okunevka: 6450,
            otradnoe: 4450,
            oliva: 4950,
            orlinoe: 4950,
            opolznevoe: 4950,
            uglovoe: 3950,
            pushkino: 3750,
            privetnoe: 4950,
            peschanoe: 3950,
            perevalnoe: 1950,
            solnechnoe: 3450,
            frunze: 3450,
            molochnoe: 4950,
            shelkino: 6950,
            mriya: 4950,
            taygan: 3950,
            alushta : 3450,
            yalta : 4450,
            evpatoriya : 4450,
            zaozernoe : 4450,
            shtormovoe : 4950,
            popovka : 4950,
            olenevka : 6450,
            chernomorskoe : 5950,
            saki : 3450,
            priboy : 3950,
            novofedorovka : 3450,
            nikolaevka : 3450,
            beregovoe_ubk : 4950,
            beregovoe_nik : 3750,
            beregovoe_feo : 4950,
            peschanoe : 3750,
            sevastopol : 4450,
            balaklava : 3950,
            orlovka : 3950,
            kacha : 3950,
            sudak : 4450,
            noviysvet: 4950,                
            feodosiya : 4450,
            kerch : 9950,
            koktebel : 4450,
            ordzhonikidze : 4950,
            ribache : 4450,
            solnechnogorskoe : 4450,
            malorechenskoe : 4450,
            partenit : 3750,
            gurzuf : 3950,
            livadiya : 4150,
            gaspra : 4950,
            alupka : 4950,
            simeiz : 4950,
            kaciveli : 4950,
            ponizovka : 4950,
            sanatornoye : 4950,
            foros : 4950
        }
    },
    minivan: {
        // aero: {
            // andreevka: ,
            // aidanil; ,
            // bahchisaray; ,
            // belogorsk; ,
            // vilino; ,
            // krasnokamenka; ,
            // karasan; ,
            // koreiz; ,
            // kurpaty; ,
            // krasnogvardeiskoe; ,
            // laspi; ,
            // lenino; ,
            // lineinoe; ,
            // lybimovka; ,
            // maliymayak; ,
            // mishor; ,
            // mirniy; ,
            // massandra; ,
            // novoozernoe; ,
            // niznayaoreanda; ,
            // nikita; ,
            // okunevka; ,
            // otradnoe; ,
            // oliva; ,
            // orlinoe; ,
            // opolznevoe; ,
            // uglovoe: ,
            // pushkino: ,
            // privetnoe: ,
            // peschanoe: ,
            // perevalnoe: ,
            // solnechnoe: ,
            // frunze: ,
            // molochnoe: ,
            // shelkino: ,
            // mriya: ,
            // taygan: ,
        //     alushta : 2800,
        //     yalta : 3700,
        //     evpatoriya : 2800,
        //     zaozernoe : 3100,
        //     shtormovoe : 3700,
        //     popovka : 3600,
        //     olenevka : 4900,
        //     chernomorskoe : 4500,
        //     saki : 2900,
        //     priboy : 2700,
        //     novofedorovka : 2600,
        //     nikolaevka : 2500,
        //     beregovoe_ubk : 4300,
        //     beregovoe_nik : 2800,
        //     beregovoe_feo : 4500,
        //     peschanoe : 2900,
        //     sevastopol : 4000,
        //     balaklava : 3900,
        //     orlovka : 3000,
        //     kacha : 3000,
        //     sudak : 3900,
        //     noviysvet: 4300,                
        //     feodosiya : 4300,
        //     kerch : 6500,
        //     koktebel : 4300,
        //     ordzhonikidze : 4400,
        //     ribache : 3800,
        //     solnechnogorskoe : 3800,
        //     malorechenskoe : 3800,
        //     partenit : 3000,
        //     gurzuf : 3200,
        //     livadiya : 3900,
        //     gaspra : 4000,
        //     alupka : 4200,
        //     simeiz : 4200,
        //     kaciveli : 4200,
        //     ponizovka : 4200,
        //     sanatornoye : 4200,
        //     foros : 4200
        // },
        trainstation: {
            andreevka: 2950,
            aidanil: 3250,
            bahchisaray: 2550,
            belogorsk: 2550,
            vilino: 2950,
            krasnokamenka: 3450,
            karasan: 2950,
            koreiz: 3950,
            kurpaty: 3950,
            krasnogvardeiskoe: 2950,
            laspi: 3950,
            lenino: 5450,
            lineinoe: 3950,
            lybimovka: 2950,
            maliymayak: 2950,
            mishor: 3950,
            mirniy: 3950,
            massandra: 3450,
            novoozernoe: 3950,
            niznayaoreanda: 3950,
            nikita: 3450,
            okunevka: 5450,
            otradnoe: 3450,
            oliva: 3950,
            orlinoe: 3950,
            opolznevoe: 3950,
            uglovoe: 2950,
            pushkino: 2450,
            privetnoe: 3950,
            peschanoe: 2950,
            perevalnoe: 1450,
            solnechnoe: 2750,
            frunze: 2450,
            molochnoe: 3950,
            shelkino: 5950,
            mriya: 3950,
            taygan: 2950,
            alushta : 2550,
            yalta : 3450,
            evpatoriya : 2950,
            zaozernoe : 2950,
            shtormovoe : 3950,
            popovka : 3950,
            olenevka : 5450,
            chernomorskoe : 4950,
            saki : 2550,
            priboy : 2950,
            novofedorovka : 2950,
            nikolaevka : 2550,
            beregovoe_ubk : 3950,
            beregovoe_nik : 2950,
            beregovoe_feo : 3950,
            peschanoe : 2950,
            sevastopol : 3450,
            balaklava : 3350,
            orlovka : 2950,
            kacha : 2950,
            sudak : 3450,
            noviysvet: 3950,                
            feodosiya : 3450,
            kerch : 7950,
            koktebel : 3450,
            ordzhonikidze : 3950,
            ribache : 3450,
            solnechnogorskoe : 3450,
            malorechenskoe : 3450,
            partenit : 2950,
            gurzuf : 3250,
            livadiya : 3450,
            gaspra : 3950,
            alupka : 3950,
            simeiz : 3950,
            kaciveli : 3950,
            ponizovka : 3950,
            sanatornoye : 3950,
            foros : 3950
        }
    }
};