export const price = {
    econom: {
        aero: {
            // andreevka: ,
            // aidanil; ,
            // bahchisaray; ,
            // belogorsk; ,
            // vilino; ,
            // krasnokamenka; ,
            // karasan; ,
            // koreiz; ,
            // kurpaty; ,
            // krasnogvardeiskoe; ,
            // laspi; ,
            // lenino; ,
            // lineinoe; ,
            // lybimovka; ,
            // maliymayak; ,
            // mishor; ,
            // mirniy; ,
            // massandra; ,
            // novoozernoe; ,
            // niznayaoreanda; ,
            // nikita; ,
            // okunevka; ,
            // otradnoe; ,
            // oliva; ,
            // orlinoe; ,
            // opolznevoe; ,
            // uglovoe: ,
            // pushkino: ,
            // privetnoe: ,
            // peschanoe: ,
            // perevalnoe: ,
            // solnechnoe: ,
            // frunze: ,
            // molochnoe: ,
            // shelkino: ,
            // mriya: ,
            // taygan: ,
            alushta : 1600,
            yalta : 2300,
            evpatoriya : 1800,
            zaozernoe : 2100,
            shtormovoe : 2200,
            popovka : 2400,
            olenevka : 3300,
            chernomorskoe : 3100,
            saki : 1500,
            priboy : 1600,
            novofedorovka : 1500,
            nikolaevka : 1500,
            beregovoe_ubk : 2500,
            beregovoe_nik : 1600,
            beregovoe_feo : 3200,
            peschanoe : 1700,
            sevastopol : 2300,
            balaklava : 2300,
            orlovka : 2000,
            kacha : 2000,
            sudak : 2500,
            noviysvet: 2700,                
            feodosiya : 3000,
            kerch : 4500,
            koktebel : 3000,
            ordzhonikidze : 3000,
            ribache : 2500,
            solnechnogorskoe : 2300,
            malorechenskoe : 2300,
            partenit : 1700,
            gurzuf : 1800,
            livadiya : 2400,
            gaspra : 2500,
            alupka : 2600,
            simeiz : 2600,
            kaciveli : 2600,
            ponizovka : 2600,
            sanatornoye : 2600,
            foros : 2600
        },
        trainstation: {
            andreevka: 1650,
            aidanil: 1950,
            bahchisaray: 1250,
            belogorsk: 1250,
            vilino: 1650,
            krasnokamenka: 1950,
            karasan: 1650,
            koreiz: 2450,
            kurpaty: 2450,
            krasnogvardeiskoe: 1950,
            laspi: 2450,
            lenino: 3250,
            lineinoe: 2450,
            lybimovka: 1950,
            maliymayak: 1650,
            mishor: 2450,
            mirniy: 2450,
            massandra: 2150,
            novoozernoe: 2450,
            niznayaoreanda: 2450,
            nikita: 1950,
            okunevka: 2450,
            otradnoe: 2150,
            oliva: 2450,
            orlinoe: 2450,
            opolznevoe: 2450,
            uglovoe: 1750,
            pushkino: 1650,
            privetnoe: 2450,
            peschanoe: 1650,
            perevalnoe: 950,
            solnechnoe: 1850,
            frunze: 1650,
            molochnoe: 2450,
            shelkino: 3450,
            mriya: 2450,
            taygan: 1950,
            alushta : 1250,
            yalta : 2250,
            evpatoriya : 1950,
            zaozernoe : 2150,
            shtormovoe : 2450,
            popovka : 2450,
            olenevka : 2950,
            chernomorskoe : 2650,
            saki : 1250,
            priboy : 1650,
            novofedorovka : 1450,
            nikolaevka : 1250,
            beregovoe_ubk : 2450,
            beregovoe_nik : 1650,
            beregovoe_feo : 2450,
            peschanoe : 1650,
            sevastopol : 2250,
            balaklava : 2150,
            orlovka : 1650,
            kacha : 1650,
            sudak : 2250,
            noviysvet: 2450,                
            feodosiya : 2250,
            kerch : 4950,
            koktebel : 2250,
            ordzhonikidze : 2450,
            ribache : 2250,
            solnechnogorskoe : 2250,
            malorechenskoe : 2250,
            partenit : 1650,
            gurzuf : 1950,
            livadiya : 2150,
            gaspra : 2450,
            alupka : 2450,
            simeiz : 2450,
            kaciveli : 2450,
            ponizovka : 2450,
            sanatornoye : 2450,
            foros : 2450
        }
    },
    comfort: {
        aero: {
            // andreevka: ,
            // aidanil; ,
            // bahchisaray; ,
            // belogorsk; ,
            // vilino; ,
            // krasnokamenka; ,
            // karasan; ,
            // koreiz; ,
            // kurpaty; ,
            // krasnogvardeiskoe; ,
            // laspi; ,
            // lenino; ,
            // lineinoe; ,
            // lybimovka; ,
            // maliymayak; ,
            // mishor; ,
            // mirniy; ,
            // massandra; ,
            // novoozernoe; ,
            // niznayaoreanda; ,
            // nikita; ,
            // okunevka; ,
            // otradnoe; ,
            // oliva; ,
            // orlinoe; ,
            // opolznevoe; ,
            // uglovoe: ,
            // pushkino: ,
            // privetnoe: ,
            // peschanoe: ,
            // perevalnoe: ,
            // solnechnoe: ,
            // frunze: ,
            // molochnoe: ,
            // shelkino: ,
            // mriya: ,
            // taygan: ,
            alushta : 1600,
            yalta : 2300,
            evpatoriya : 1800,
            zaozernoe : 2100,
            shtormovoe : 2200,
            popovka : 2400,
            olenevka : 3300,
            chernomorskoe : 3100,
            saki : 1500,
            priboy : 1600,
            novofedorovka : 1500,
            nikolaevka : 1500,
            beregovoe_ubk : 2500,
            beregovoe_nik : 1600,
            beregovoe_feo : 3200,
            peschanoe : 1700,
            sevastopol : 2300,
            balaklava : 2300,
            orlovka : 2000,
            kacha : 2000,
            sudak : 2500,
            noviysvet: 2700,                
            feodosiya : 3000,
            kerch : 4500,
            koktebel : 3000,
            ordzhonikidze : 3000,
            ribache : 2500,
            solnechnogorskoe : 2300,
            malorechenskoe : 2300,
            partenit : 1700,
            gurzuf : 1800,
            livadiya : 2400,
            gaspra : 2500,
            alupka : 2600,
            simeiz : 2600,
            kaciveli : 2600,
            ponizovka : 2600,
            sanatornoye : 2600,
            foros : 2600
        },
        trainstation: {
            andreevka: ,
            aidanil; ,
            bahchisaray; ,
            belogorsk; ,
            vilino; ,
            krasnokamenka; ,
            karasan; ,
            koreiz; ,
            kurpaty; ,
            krasnogvardeiskoe; ,
            laspi; ,
            lenino; ,
            lineinoe; ,
            lybimovka; ,
            maliymayak; ,
            mishor; ,
            mirniy; ,
            massandra; ,
            novoozernoe; ,
            niznayaoreanda; ,
            nikita; ,
            okunevka; ,
            otradnoe; ,
            oliva; ,
            orlinoe; ,
            opolznevoe; ,
            uglovoe: ,
            pushkino: ,
            privetnoe: ,
            peschanoe: ,
            perevalnoe: ,
            solnechnoe: ,
            frunze: ,
            molochnoe: ,
            shelkino: ,
            mriya: ,
            taygan: ,
            alushta : 1600,
            yalta : 2200,
            evpatoriya : 2000,
            zaozernoe : 2200,
            shtormovoe : 2300,
            popovka : 2500,
            olenevka : 3500,
            chernomorskoe : 3500,
            saki : 1500,
            priboy : 1700,
            novofedorovka : 1500,
            nikolaevka : 1500,
            beregovoe_ubk : 2500,
            beregovoe_nik : 1600,
            beregovoe_feo : 3200,
            peschanoe : 1600,
            sevastopol : 2200,
            balaklava : 2200,
            orlovka : 2000,
            kacha : 2000,
            sudak : 2500,
            noviysvet: 2700,                
            feodosiya : 3000,
            kerch : 4500,
            koktebel : 3000,
            ordzhonikidze : 3000,
            ribache : 2500,
            solnechnogorskoe : 2300,
            malorechenskoe : 2300,
            partenit : 1700,
            gurzuf : 1800,
            livadiya : 2400,
            gaspra : 2500,
            alupka : 2600,
            simeiz : 2600,
            kaciveli : 2600,
            ponizovka : 2600,
            sanatornoye : 2600,
            foros : 2600
        }
    },
    business: {
        aero: {
            // andreevka: ,
            // aidanil; ,
            // bahchisaray; ,
            // belogorsk; ,
            // vilino; ,
            // krasnokamenka; ,
            // karasan; ,
            // koreiz; ,
            // kurpaty; ,
            // krasnogvardeiskoe; ,
            // laspi; ,
            // lenino; ,
            // lineinoe; ,
            // lybimovka; ,
            // maliymayak; ,
            // mishor; ,
            // mirniy; ,
            // massandra; ,
            // novoozernoe; ,
            // niznayaoreanda; ,
            // nikita; ,
            // okunevka; ,
            // otradnoe; ,
            // oliva; ,
            // orlinoe; ,
            // opolznevoe; ,
            // uglovoe: ,
            // pushkino: ,
            // privetnoe: ,
            // peschanoe: ,
            // perevalnoe: ,
            // solnechnoe: ,
            // frunze: ,
            // molochnoe: ,
            // shelkino: ,
            // mriya: ,
            // taygan: ,
            alushta : 1600,
            yalta : 2300,
            evpatoriya : 1800,
            zaozernoe : 2100,
            shtormovoe : 2200,
            popovka : 2400,
            olenevka : 3300,
            chernomorskoe : 3100,
            saki : 1500,
            priboy : 1600,
            novofedorovka : 1500,
            nikolaevka : 1500,
            beregovoe_ubk : 2500,
            beregovoe_nik : 1600,
            beregovoe_feo : 3200,
            peschanoe : 1700,
            sevastopol : 2300,
            balaklava : 2300,
            orlovka : 2000,
            kacha : 2000,
            sudak : 2500,
            noviysvet: 2700,                
            feodosiya : 3000,
            kerch : 4500,
            koktebel : 3000,
            ordzhonikidze : 3000,
            ribache : 2500,
            solnechnogorskoe : 2300,
            malorechenskoe : 2300,
            partenit : 1700,
            gurzuf : 1800,
            livadiya : 2400,
            gaspra : 2500,
            alupka : 2600,
            simeiz : 2600,
            kaciveli : 2600,
            ponizovka : 2600,
            sanatornoye : 2600,
            foros : 2600
        },
        trainstation: {
            andreevka: ,
            aidanil; ,
            bahchisaray; ,
            belogorsk; ,
            vilino; ,
            krasnokamenka; ,
            karasan; ,
            koreiz; ,
            kurpaty; ,
            krasnogvardeiskoe; ,
            laspi; ,
            lenino; ,
            lineinoe; ,
            lybimovka; ,
            maliymayak; ,
            mishor; ,
            mirniy; ,
            massandra; ,
            novoozernoe; ,
            niznayaoreanda; ,
            nikita; ,
            okunevka; ,
            otradnoe; ,
            oliva; ,
            orlinoe; ,
            opolznevoe; ,
            uglovoe: ,
            pushkino: ,
            privetnoe: ,
            peschanoe: ,
            perevalnoe: ,
            solnechnoe: ,
            frunze: ,
            molochnoe: ,
            shelkino: ,
            mriya: ,
            taygan: ,
            alushta : 1600,
            yalta : 2200,
            evpatoriya : 2000,
            zaozernoe : 2200,
            shtormovoe : 2300,
            popovka : 2500,
            olenevka : 3500,
            chernomorskoe : 3500,
            saki : 1500,
            priboy : 1700,
            novofedorovka : 1500,
            nikolaevka : 1500,
            beregovoe_ubk : 2500,
            beregovoe_nik : 1600,
            beregovoe_feo : 3200,
            peschanoe : 1600,
            sevastopol : 2200,
            balaklava : 2200,
            orlovka : 2000,
            kacha : 2000,
            sudak : 2500,
            noviysvet: 2700,                
            feodosiya : 3000,
            kerch : 4500,
            koktebel : 3000,
            ordzhonikidze : 3000,
            ribache : 2500,
            solnechnogorskoe : 2300,
            malorechenskoe : 2300,
            partenit : 1700,
            gurzuf : 1800,
            livadiya : 2400,
            gaspra : 2500,
            alupka : 2600,
            simeiz : 2600,
            kaciveli : 2600,
            ponizovka : 2600,
            sanatornoye : 2600,
            foros : 2600
        }
    },
    minivan: {
        aero: {
            // andreevka: ,
            // aidanil; ,
            // bahchisaray; ,
            // belogorsk; ,
            // vilino; ,
            // krasnokamenka; ,
            // karasan; ,
            // koreiz; ,
            // kurpaty; ,
            // krasnogvardeiskoe; ,
            // laspi; ,
            // lenino; ,
            // lineinoe; ,
            // lybimovka; ,
            // maliymayak; ,
            // mishor; ,
            // mirniy; ,
            // massandra; ,
            // novoozernoe; ,
            // niznayaoreanda; ,
            // nikita; ,
            // okunevka; ,
            // otradnoe; ,
            // oliva; ,
            // orlinoe; ,
            // opolznevoe; ,
            // uglovoe: ,
            // pushkino: ,
            // privetnoe: ,
            // peschanoe: ,
            // perevalnoe: ,
            // solnechnoe: ,
            // frunze: ,
            // molochnoe: ,
            // shelkino: ,
            // mriya: ,
            // taygan: ,
            alushta : 2800,
            yalta : 3700,
            evpatoriya : 2800,
            zaozernoe : 3100,
            shtormovoe : 3700,
            popovka : 3600,
            olenevka : 4900,
            chernomorskoe : 4500,
            saki : 2900,
            priboy : 2700,
            novofedorovka : 2600,
            nikolaevka : 2500,
            beregovoe_ubk : 4300,
            beregovoe_nik : 2800,
            beregovoe_feo : 4500,
            peschanoe : 2900,
            sevastopol : 4000,
            balaklava : 3900,
            orlovka : 3000,
            kacha : 3000,
            sudak : 3900,
            noviysvet: 4300,                
            feodosiya : 4300,
            kerch : 6500,
            koktebel : 4300,
            ordzhonikidze : 4400,
            ribache : 3800,
            solnechnogorskoe : 3800,
            malorechenskoe : 3800,
            partenit : 3000,
            gurzuf : 3200,
            livadiya : 3900,
            gaspra : 4000,
            alupka : 4200,
            simeiz : 4200,
            kaciveli : 4200,
            ponizovka : 4200,
            sanatornoye : 4200,
            foros : 4200
        },
        trainstation: {
            andreevka: ,
            aidanil; ,
            bahchisaray; ,
            belogorsk; ,
            vilino; ,
            krasnokamenka; ,
            karasan; ,
            koreiz; ,
            kurpaty; ,
            krasnogvardeiskoe; ,
            laspi; ,
            lenino; ,
            lineinoe; ,
            lybimovka; ,
            maliymayak; ,
            mishor; ,
            mirniy; ,
            massandra; ,
            novoozernoe; ,
            niznayaoreanda; ,
            nikita; ,
            okunevka; ,
            otradnoe; ,
            oliva; ,
            orlinoe; ,
            opolznevoe; ,
            uglovoe: ,
            pushkino: ,
            privetnoe: ,
            peschanoe: ,
            perevalnoe: ,
            solnechnoe: ,
            frunze: ,
            molochnoe: ,
            shelkino: ,
            mriya: ,
            taygan: ,
            alushta : 2800,
            yalta : 3700,
            evpatoriya : 2800,
            zaozernoe : 3100,
            shtormovoe : 3700,
            popovka : 3600,
            olenevka : 4900,
            chernomorskoe : 4500,
            saki : 2900,
            priboy : 2700,
            novofedorovka : 2600,
            nikolaevka : 2500,
            beregovoe_ubk : 4300,
            beregovoe_nik : 2800,
            beregovoe_feo : 4500,
            peschanoe : 2900,
            sevastopol : 4000,
            balaklava : 3900,
            orlovka : 3000,
            kacha : 3000,
            sudak : 3900,
            noviysvet: 4300,                
            feodosiya : 4300,
            kerch : 6500,
            koktebel : 4300,
            ordzhonikidze : 4400,
            ribache : 3800,
            solnechnogorskoe : 3800,
            malorechenskoe : 3800,
            partenit : 3000,
            gurzuf : 3200,
            livadiya : 3900,
            gaspra : 4000,
            alupka : 4200,
            simeiz : 4200,
            kaciveli : 4200,
            ponizovka : 4200,
            sanatornoye : 4200,
            foros : 4200
        }
    }
};